apiVersion: v1
kind: Service

metadata:
  name: orders-service
  namespace: microservices-demo

spec:
  selector:
    app: orders-service

  ports:
  - port: 3002
    targetPort: 3002

  type: ClusterIP